"""'v.3.0'

Revision ID: 6d5d7ed0e43a
Revises: 7d5308eeceb3
Create Date: 2022-11-07 01:04:20.250724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5d7ed0e43a'
down_revision = '7d5308eeceb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('editors_user_id_fkey', 'editors', type_='foreignkey')
    op.drop_constraint('editors_note_id_fkey', 'editors', type_='foreignkey')
    op.create_foreign_key(None, 'editors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'editors', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_owner_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tag_note_note_id_fkey', 'tag_note', type_='foreignkey')
    op.drop_constraint('tag_note_tag_id_fkey', 'tag_note', type_='foreignkey')
    op.create_foreign_key(None, 'tag_note', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_note', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_note', type_='foreignkey')
    op.drop_constraint(None, 'tag_note', type_='foreignkey')
    op.create_foreign_key('tag_note_tag_id_fkey', 'tag_note', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tag_note_note_id_fkey', 'tag_note', 'notes', ['note_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_owner_id_fkey', 'notes', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'editors', type_='foreignkey')
    op.drop_constraint(None, 'editors', type_='foreignkey')
    op.create_foreign_key('editors_note_id_fkey', 'editors', 'notes', ['note_id'], ['id'])
    op.create_foreign_key('editors_user_id_fkey', 'editors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
