"""v3.0

Revision ID: 7d5308eeceb3
Revises: e200d85d53aa
Create Date: 2022-11-06 18:37:16.569693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5308eeceb3'
down_revision = 'e200d85d53aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
