"""v2.0

Revision ID: e200d85d53aa
Revises: 6031ff722f35
Create Date: 2022-11-06 17:11:25.647493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e200d85d53aa'
down_revision = '6031ff722f35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_owner_id_key', 'notes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('notes_owner_id_key', 'notes', ['owner_id'])
    # ### end Alembic commands ###
